name: Docker Build

on:
  push:
    branches: ["main"]

jobs:


  build:


    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build Docker Img
        run: |
          docker build -t tmaior-test .
      - name: Tag Docker Image
        run: docker tag tmaior-test jhbm/tmaior-test:latest

      - name: Push Docker Img
        env:
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run:
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            
            docker push jhbm/tmaior-test:latest
          

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: connect EC2 to Githubactions
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop $(docker ps -q)
            docker pull jhbm/tmaior-test:latest
            docker run -d -p 5000:5000 jhbm/tmaior-test:latest